const ACCESS_TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmMzMTdjYTVlYjk5ODViZTdjNmM1NyIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInJvbGUiOiJvcmdhbml6ZXIiLCJpYXQiOjE3MTgzNjY1ODh9.x3shv4Y-dgO4segjjreI_wA7SdhvSyQfP9m8KLLhrTM";

module.exports = ACCESS_TOKEN;
